// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stage.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Stage _$StageFromJson(Map<String, dynamic> json) {
  return Stage(
    stageType: json['stageType'] as String? ?? '',
    difficulty: json['difficulty'] as String? ?? '',
    performanceStageFlag: json['performanceStageFlag'] as String? ?? '',
    stageId: json['stageId'] as String? ?? '',
    levelId: json['levelId'] as String? ?? '',
    zoneId: json['zoneId'] as String? ?? '',
    code: json['code'] as String? ?? '',
    name: json['name'] as String? ?? '',
    description: json['description'] as String? ?? '',
    hardStagedId: json['hardStagedId'] as String?,
    dangerLevel: json['dangerLevel'] as String?,
    dangerPoint: (json['dangerPoint'] as num?)?.toDouble(),
    loadingPicId: json['loadingPicId'] as String?,
    canPractice: json['canPractice'] as bool,
    canBattleReplay: json['canBattleReplay'] as bool,
    apCost: json['apCost'] as int,
    apFailReturn: json['apFailReturn'] as int,
    etCost: json['etCost'] as int,
    etFailReturn: json['etFailReturn'] as int,
    apProtectTimes: json['apProtectTimes'] as int,
    diamondOnceDrop: json['diamondOnceDrop'] as int,
    practiceTicketCost: json['practiceTicketCost'] as int,
    dailyStageDifficulty: json['dailyStageDifficulty'] as int,
    expGain: json['expGain'] as int,
    goldGain: json['goldGain'] as int,
    loseExpGain: json['loseExpGain'] as int,
    loseGoldGain: json['loseGoldGain'] as int,
    passFavor: json['passFavor'] as int,
    completeFavor: json['completeFavor'] as int,
    slProgress: json['slProgress'] as int,
    displayMainItem: json['displayMainItem'] as String?,
    hilightMark: json['hilightMark'] as bool,
    bossMark: json['bossMark'] as bool,
    isPredefined: json['isPredefined'] as bool,
    isHardPredefined: json['isHardPredefined'] as bool,
    isStoryOnly: json['isStoryOnly'] as bool,
    appearanceStyle: json['appearanceStyle'] as int,
    stageDropInfo: json['stageDropInfo'] == null
        ? null
        : StageDrop.fromJson(json['stageDropInfo'] as Map<String, dynamic>),
    isStagePatch: json['isStagePatch'] as bool,
    mainStageId: json['mainStageId'] as String? ?? '',
  );
}

Map<String, dynamic> _$StageToJson(Stage instance) => <String, dynamic>{
      'stageType': instance.stageType,
      'difficulty': instance.difficulty,
      'performanceStageFlag': instance.performanceStageFlag,
      'stageId': instance.stageId,
      'levelId': instance.levelId,
      'zoneId': instance.zoneId,
      'code': instance.code,
      'name': instance.name,
      'description': instance.description,
      'hardStagedId': instance.hardStagedId,
      'dangerLevel': instance.dangerLevel,
      'dangerPoint': instance.dangerPoint,
      'loadingPicId': instance.loadingPicId,
      'canPractice': instance.canPractice,
      'canBattleReplay': instance.canBattleReplay,
      'apCost': instance.apCost,
      'apFailReturn': instance.apFailReturn,
      'etCost': instance.etCost,
      'etFailReturn': instance.etFailReturn,
      'apProtectTimes': instance.apProtectTimes,
      'diamondOnceDrop': instance.diamondOnceDrop,
      'practiceTicketCost': instance.practiceTicketCost,
      'dailyStageDifficulty': instance.dailyStageDifficulty,
      'expGain': instance.expGain,
      'goldGain': instance.goldGain,
      'loseExpGain': instance.loseExpGain,
      'loseGoldGain': instance.loseGoldGain,
      'passFavor': instance.passFavor,
      'completeFavor': instance.completeFavor,
      'slProgress': instance.slProgress,
      'displayMainItem': instance.displayMainItem,
      'hilightMark': instance.hilightMark,
      'bossMark': instance.bossMark,
      'isPredefined': instance.isPredefined,
      'isHardPredefined': instance.isHardPredefined,
      'isStoryOnly': instance.isStoryOnly,
      'appearanceStyle': instance.appearanceStyle,
      'stageDropInfo': instance.stageDropInfo,
      'isStagePatch': instance.isStagePatch,
      'mainStageId': instance.mainStageId,
    };
